### ISSUE TITLE
Current Development and contributions

### ISSUE THREAD

**Issue by gwenf** [wallabyway/rn-opencv-demo#3]
I saw some other questions over the last few months about the status of this project but I haven't seen any recent activity. Is this project currently under development? And is there anything I can do to help you get this out?

**Comment by vaibhawc** [comment]
Yeah me too.

**Comment by pgarciacamou** [comment]
@ugiacoman

**Comment by ugiacoman** [comment]
@gwenf @vaibhawc @pgarciacamou Hey guys, sorry for the lack of updates. I haven't been able to give this project the attention it deserves. If anyone wants to take it up, by all means!

**Comment by pgarciacamou** [comment]
@ugiacoman you can transfer it to me. I'm going to be working with react-native a lot more in the next few weeks and would love to work on this 👍

**Comment by pgarciacamou** [comment]
I know there is a lot of people waiting for this, I haven't had time to start it just yet, but I have to soon.

PRs are also welcomed, although it is too soon for anyone to be able to pitch in. I'll keep you posted.

**Comment by ducpt2** [comment]
@pgarciacamou love it :)

**Comment by pgarciacamou** [comment]
⚠️

Unfortunately, I just found out that the project that I was going to start that needed this module was canceled and I do not have more free time to work on this.

Let me know if there is anyone that wants to start working on it and I'll transfer this repo and [npm module](https://www.npmjs.com/package/react-native-opencv) as well.

**Comment by ma-pe** [comment]
Hey @pgarciacamou, 

I am planning to work on an OpenCV integration for react-native in the following months. I would be happy to start working on this repo.

**Comment by pgarciacamou** [comment]
@ma-pe transfered, what is your npm account?

**Comment by ma-pe** [comment]
@pgarciacamou Thank you.

There you go: https://www.npmjs.com/~malte_peters

**Comment by ma-pe** [comment]
I will close this for now. 

In the upcoming weeks I'll design a potential API. In the following months I'll start implementing it -
 **iOS first**. It is too early to predict a potential alpha release though.
